### ISSUE TITLE
manifest merged failed 

### ISSUE THREAD

**Issue by Isma3ilMohamed** [harrylefit/bottomnavigation#1]
hey @harrylefit 
first of all 
thank you for making bottom navigation implementation easily 
but when i implement it 
i see this issue
Manifest merger failed : uses-sdk:minSdkVersion 19 cannot be smaller than version 21 declared in library [com.github.harrylefit:bottomnavigation:1.1.6] C:\Users\User\.gradle\caches\transforms-1\files-1.1\bottomnavigation-1.1.6.aar\d4d38b5db3161eb339253edede02351a\AndroidManifest.xml as the library might be using APIs not available in 19
	Suggestion: use a compatible library with a minSdk of at most 19,
		or increase this project's minSdk version to at least 21,
		or use tools:overrideLibrary="harryle.eazy.vn.bottomnavigation" to force usage (may lead to runtime failures)

i know it can solved by increase min sdk version to 21
but i use 19 to make app compatible on more devices
so can you reduce it !!???

**Comment by harrylefit** [comment]
> hey @harrylefit
> first of all
> thank you for making bottom navigation implementation easily
> but when i implement it
> i see this issue
> Manifest merger failed : uses-sdk:minSdkVersion 19 cannot be smaller than version 21 declared in library [com.github.harrylefit:bottomnavigation:1.1.6] C:\Users\User.gradle\caches\transforms-1\files-1.1\bottomnavigation-1.1.6.aar\d4d38b5db3161eb339253edede02351a\AndroidManifest.xml as the library might be using APIs not available in 19
> Suggestion: use a compatible library with a minSdk of at most 19,
> or increase this project's minSdk version to at least 21,
> or use tools:overrideLibrary="harryle.eazy.vn.bottomnavigation" to force usage (may lead to runtime failures)
> 
> i know it can solved by increase min sdk version to 21
> but i use 19 to make app compatible on more devices
> so can you reduce it !!???

Hi @Isma3ilMohamed , 
Thank

**Comment by harrylefit** [comment]
Hi @Isma3ilMohamed , 
Thank you for feed back. I've updated min sdk version. I updated also Readme.md for new release version (1.1.6.1).

**Comment by Isma3ilMohamed** [comment]
yes it worked now
thanks bro @harrylefit
