### ISSUE TITLE
can't see bottom navigation

### ISSUE THREAD

**Issue by Isma3ilMohamed** [harrylefit/bottomnavigation#2]
hey @harrylefit 
first of all thanks for reduce min sdk
but now i can't see bottom navigation view
when i try to use your sample
the activity show big white space without this view

**Comment by harrylefit** [comment]
Hi Ismail Mohamed,
Can you send screenshot for me? I've checked source code but it's working
now.

**Comment by Isma3ilMohamed** [comment]
hi @harrylefit 
sorry for late i just see your message now
i take to screenshot from emulator and from design screen on android studio
![1](https://user-images.githubusercontent.com/34917869/49797187-62fc3000-fd47-11e8-85f6-fd3e970015ed.PNG)
![screenshot_1544527061](https://user-images.githubusercontent.com/34917869/49797189-6394c680-fd47-11e8-9719-3b99d81e7fac.png)
and that is xml 
[code]
<?xml version="1.0" encoding="utf-8"?>
<android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".ui.activity.NavActivity">


    <harryle.eazy.vn.bottomnavigation.navigation.BottomNavigation
        android:id="@+id/nav"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:layout_alignParentBottom="true"
        app:activeColor="@android:color/white"
        app:backgroundNavigation="@color/colorAccent"
        app:defaultSelectedPosition="0"
        app:inActiveColor="#80FFFFFF"
        app:resMenu="@menu/main_menu"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:mode="normal"
        app:textFontFamily="@font/semibold"
        tools:layout_height="56dp" />

</android.support.constraint.ConstraintLayout>
[/code]

**Comment by harrylefit** [comment]
Hi @Isma3ilMohamed,
For design mode, it's white space because we haven't set a menu for it.
You must programmatically set menu `nav.setMenu(R.menu.nav)`, just follow `MainActivtiy` on example project.

**Comment by Isma3ilMohamed** [comment]
yes it's worked now
thank you 👏👏
but why menu need to set from code not xml

**Comment by harrylefit** [comment]
Have some issues so I'm looking for the best implementation in XML. Will let you know if it's done.

**Comment by harrylefit** [comment]
Hi @Isma3ilMohamed,
I've supported set menu in XML. you can check this with new release version (1.1.7)
