### ISSUE TITLE
Not  replace the other fragment of onClick of bottom  navigation.

### ISSUE THREAD

**Issue by rajam1215** [harrylefit/bottomnavigation#5]
When click on second item of bottom navigation . there is need to replace other fragment like 

on first item show first fragment and click on second item go to second fragment .

like pager, when scroll pager: fragment scroll

but on click of bottom navigation item fragment not replace, not work

please look in to it

**Comment by harrylefit** [comment]
HI @rajam1215, did you handle listener when you clicked the item of bottom navigation? 
You can use `bottom_bar?.setOnNavigationListener(OnNavigationListener)` and handle this listener when you clicked it and you can replace fragment or do something like this inside this listener.

**Comment by rajam1215** [comment]
Hello @harrylefit 

i can change with my code with replace.fragment

i want you do that thing in library so new user or beginner use your library in friendly way.

Thanks

**Comment by rajam1215** [comment]
please update the **READ.MD** file with new feature of library like Mode **View pager, scroll able false etc** after that you can close that issue.
